# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/jupyter-cloud-creds/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"

python:
  install:
    - requirements: docs/requirements.txt
